name: CI Build and Test Matrix Project

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout source code
        uses: actions/checkout@v3

      # Step 2: Install dependencies on Ubuntu
      - name: Install dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          if ! command -v cmake &> /dev/null; then
            echo "CMake not found. Installing..."
            sudo apt-get install -y cmake
          fi

          if ! command -v gcc &> /dev/null; then
            echo "GCC not found. Installing..."
            sudo apt-get install -y build-essential
          fi

          if ! command -v g++ &> /dev/null; then
            echo "G++ not found. Installing..."
            sudo apt-get install -y build-essential
          fi

      # Step 3: Install dependencies on Windows
      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          if (-not (Get-Command cmake -ErrorAction SilentlyContinue)) {
            Write-Host "CMake not found. Installing via Chocolatey..."
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          }

          if (-not (Get-Command gcc -ErrorAction SilentlyContinue)) {
            Write-Host "GCC not found. Installing MinGW..."
            choco install mingw
          }

          if (-not (Get-Command g++ -ErrorAction SilentlyContinue)) {
            Write-Host "G++ not found. Installing MinGW..."
            choco install mingw
          }

      # Step 4: Configure the build with CMake
      - name: Configure with CMake on Linux
        if: runner.os == 'Linux'
        run: |
          cmake -S . -B build

      - name: Configure with CMake on Windows
        if: runner.os == 'Windows'
        run: |
          cmake -S . -B build -G "MinGW Makefiles"

      # Step 5: Build the project
      - name: Build with CMake on Linux
        if: runner.os == 'Linux'
        run: |
          cmake --build build

      - name: Build with CMake on Windows
        if: runner.os == 'Windows'
        run: |
          cmake --build build

      # Step 6: Run tests and dump output to result.txt
      - name: Run Tests and Dump Output
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            if [ -f ./build/matrix_lib ]; then
              ./build/matrix_lib > result.txt
            else
              echo "Executable not found. Please check the build."
              exit 1
            fi
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            if (Test-Path .\build\matrix_lib.exe) {
              .\build\matrix_lib.exe | Out-File -FilePath result.txt
            } else {
              Write-Host "Executable not found. Please check the build."
              exit 1
            fi
          fi

      # Step 7: Search for "ALL THE TEST PASSED"
      - name: Validate Test Results
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            if grep -q "ALL THE TEST PASSED" result.txt; then
              echo "All tests passed."
            else
              echo "Tests failed. Check the output."
              exit 1
            fi
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            if (Select-String -Path result.txt -Pattern "ALL THE TEST PASSED") {
              Write-Host "All tests passed."
            } else {
              Write-Host "Tests failed. Check the output."
              exit 1
            fi
          fi
