name: Doxygen Documentation

on:
  push:
    branches: ["dev"]

jobs:
  doxygen:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Doxygen and Graphviz (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          echo "Installing Doxygen and Graphviz on Ubuntu..."
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Set up Doxygen on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'

          # Install Chocolatey if not installed
          if (-not (Test-Path "$env:ProgramData\chocolatey\bin\choco.exe")) {
              Write-Host "Installing Chocolatey..."
              Set-ExecutionPolicy Bypass -Scope Process -Force
              [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
              Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          }

          # Install Doxygen using Chocolatey
          Write-Host "Installing Doxygen using Chocolatey..."
          choco install doxygen.install -y --source="https://community.chocolatey.org/api/v2/"

      - name: Verify Doxygen Installation
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            doxygen --version
          else
            pwsh -Command "doxygen --version"
          fi

      - name: Ensure docs/html directory exists
        run: mkdir -p docs/html

      - name: Clean up old documentation
        run: rm -rf docs/html/*

      - name: Generate documentation
        run: doxygen Doxyfile

      - name: Deploy documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: gh-pages
          folder: docs/html

