name: Doxygen Documentation

on:
  push:
    branches: ["dev"]

jobs:
  doxygen:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Doxygen and Graphviz
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            # Check if Doxygen is already installed on Ubuntu
            if ! command -v doxygen &> /dev/null; then
              echo "Doxygen not found, installing..."
              sudo apt-get update
              sudo apt-get install -y doxygen graphviz
            else
              echo "Doxygen is already installed"
            fi
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            # Add the default Chocolatey source to make sure it's available
            choco source add -n=chocolatey -s=https://community.chocolatey.org/api/v2/

            # Check if Doxygen is already installed on Windows
            if ! command -v doxygen &> /dev/null; then
              echo "Doxygen not found, installing..."
              # Ensure the correct package is installed, or use --pre if it's a prerelease
              choco install doxygen --yes --source https://community.chocolatey.org/api/v2/
            else
              echo "Doxygen is already installed"
            fi
          fi
        shell: bash

      - name: Generate documentation
        run: doxygen Doxyfile

      - name: Deploy documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: gh-pages
          folder: docs/html  # Adjust if your docs are in a different folder
