name: Doxygen Documentation

on:
  push:
    branches: ["dev"]

jobs:
  doxygen:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Doxygen and Graphviz
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            # Check if Doxygen is already installed on Ubuntu
            if ! command -v doxygen &> /dev/null; then
              echo "Doxygen not found, installing..."
              sudo apt-get update
              sudo apt-get install -y doxygen graphviz
            else
              echo "Doxygen is already installed"
            fi
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            # Install Doxygen manually on Windows
            echo "Installing Doxygen manually on Windows..."

            # Download Doxygen installer from official website
            $url = "https://github.com/doxygen/doxygen/releases/download/1.9.3/doxygen-1.9.3-setup.exe"
            $output = "doxygen-setup.exe"
            Invoke-WebRequest -Uri $url -OutFile $output

            # Run the installer silently
            Start-Process -FilePath $output -ArgumentList "/S" -Wait

            # Clean up installer
            Remove-Item -Path $output
          fi
        shell: bash

      - name: Generate documentation
        run: doxygen Doxyfile

      - name: Deploy documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: gh-pages
          folder: docs/html  # Adjust if your docs are in a different folder
