name: Doxygen Documentation

on:
  push:
    branches: ["dev"]

jobs:
  doxygen:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List installed Chocolatey packages
        shell: pwsh
        run: choco list --limit-output

      - name: Force install Doxygen with Chocolatey
        shell: pwsh
        run: |
          choco install doxygen.install -y --force --debug --verbose

      - name: Find Doxygen Installation Path
        shell: pwsh
        run: |
          Get-Command doxygen -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Definition

      - name: Manually Add Doxygen to PATH
        shell: pwsh
        run: |
          echo "C:\Program Files\Doxygen\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Verify Doxygen Installation
        shell: pwsh
        run: doxygen --version

      - name: Generate documentation
        shell: pwsh
        run: doxygen Doxyfile 2>&1 | Tee-Object -FilePath doxygen.log
