name: Build and Test C++ Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

steps:
  - name: Install CMake
    run: |
      sudo apt-get update
      sudo apt-get install -y cmake

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

    - name: Configure with CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build the project
      run: |
        make -j 

    - name: Cache build artifacts (optional)
      uses: actions/cache@v3
      with:
        path: |
          ./build 
        key: ${{ runner.os }}-build-${{ hashFiles('**/CMakeLists.txt') }} 
