name: Build and Test Matrix Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout source code
        uses: actions/checkout@v3

      # Step 2: Install CMake
      - name: Install CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      # Step 3: Install GCC and G++
      - name: Install GCC and G++
        run: |
          sudo apt-get install -y build-essential

      # Step 4: Configure the build
      - name: Configure with CMake
        run: cmake -S . -B build
